declare namespace PageRoute {
  /**
   * the root route key
   * @translate 根路由
   */
  type RootRouteKey = 'root';

  /**
   * the not found route, which catch the invalid route path
   * @translate 未找到路由(捕获无效路径的路由)
   */
  type NotFoundRouteKey = 'not-found';

  /**
   * the route key
   * @translate 页面路由
   */
  type RouteKey =
    | '403'
    | '404'
    | '500'
    | 'constant-page'
    | 'login'
    | 'not-found'
    | 'about'
    | 'alarm'
    | 'alarm_navigation'
    | 'auth-demo'
    | 'auth-demo_permission'
    | 'auth-demo_super'
    | 'component'
    | 'component_button'
    | 'component_card'
    | 'component_table'
    | 'count'
    | 'count_navigation'
    | 'dashboard'
    | 'dashboard_analysis'
    | 'document'
    | 'document_naive'
    | 'document_project-link'
    | 'document_project'
    | 'document_vite'
    | 'document_vue'
    | 'exception'
    | 'exception_403'
    | 'exception_404'
    | 'exception_500'
    | 'function'
    | 'function_tab-detail'
    | 'function_tab-multi-detail'
    | 'function_tab'
    | 'heat'
    | 'heat_homepage'
    | 'heat_warning'
    | 'ipconfig'
    | 'ipconfig_homepage'
    | 'log'
    | 'log_output'
    | 'management'
    | 'management_auth'
    | 'management_role'
    | 'management_route'
    | 'management_user'
    | 'multi-menu'
    | 'multi-menu_first'
    | 'multi-menu_first_second-new'
    | 'multi-menu_first_second-new_third'
    | 'multi-menu_first_second'
    | 'nitrogen'
    | 'nitrogen_navigation'
    | 'parameter'
    | 'parameter_furnace'
    | 'plugin'
    | 'plugin_charts'
    | 'plugin_charts_antv'
    | 'plugin_charts_echarts'
    | 'plugin_copy'
    | 'plugin_editor'
    | 'plugin_editor_markdown'
    | 'plugin_editor_quill'
    | 'plugin_icon'
    | 'plugin_map'
    | 'plugin_print'
    | 'plugin_swiper'
    | 'plugin_video'
    | 'product'
    | 'product_navigation'
    | 'profile'
    | 'profile_nitrogen'
    | 'profile_track'
    | 'profile_vacuum'
    | 'system'
    | 'system_maintain'
    | 'system_navigation'
    | 'system_oil'
    | 'track'
    | 'track_navigation'
    | 'track_organization'
    | 'user'
    | 'user_accredit'
    | 'user_login'
    | 'user_other'
    | 'vacuum'
    | 'vacuum_alarm'
    | 'vacuum_homepage'
    | 'vacuum_surplus'
    | 'vacuum_three';

  /**
   * last degree route key, which has the page file
   * @translate 最后一级路由(该级路有对应的页面文件)
   */
  type LastDegreeRouteKey = Extract<
    RouteKey,
    | '403'
    | '404'
    | '500'
    | 'constant-page'
    | 'login'
    | 'not-found'
    | 'about'
    | 'alarm_navigation'
    | 'auth-demo_permission'
    | 'auth-demo_super'
    | 'component_button'
    | 'component_card'
    | 'component_table'
    | 'count_navigation'
    | 'dashboard_analysis'
    | 'document_naive'
    | 'document_project-link'
    | 'document_project'
    | 'document_vite'
    | 'document_vue'
    | 'exception_403'
    | 'exception_404'
    | 'exception_500'
    | 'function_tab-detail'
    | 'function_tab-multi-detail'
    | 'function_tab'
    | 'heat_homepage'
    | 'heat_warning'
    | 'ipconfig_homepage'
    | 'log_output'
    | 'management_auth'
    | 'management_role'
    | 'management_route'
    | 'management_user'
    | 'multi-menu_first_second-new_third'
    | 'multi-menu_first_second'
    | 'nitrogen_navigation'
    | 'parameter_furnace'
    | 'plugin_charts_antv'
    | 'plugin_charts_echarts'
    | 'plugin_copy'
    | 'plugin_editor_markdown'
    | 'plugin_editor_quill'
    | 'plugin_icon'
    | 'plugin_map'
    | 'plugin_print'
    | 'plugin_swiper'
    | 'plugin_video'
    | 'product_navigation'
    | 'profile_nitrogen'
    | 'profile_track'
    | 'profile_vacuum'
    | 'system_maintain'
    | 'system_navigation'
    | 'system_oil'
    | 'track_navigation'
    | 'track_organization'
    | 'user_accredit'
    | 'user_login'
    | 'user_other'
    | 'vacuum_alarm'
    | 'vacuum_homepage'
    | 'vacuum_surplus'
    | 'vacuum_three'
  >;
}
